name: Continuous Integration

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scala:
    uses: nokdotie/github-workflows/.github/workflows/scala-test.yml@main
    secrets:
      GH_TOKEN_READ_PACKAGES: ${{ secrets.GH_TOKEN_READ_PACKAGES }}
